####################################################
# Even Fibonacci Numbers
#
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
######################################################

# 1st step build the fibonacci sequence

sequence = [1,2]
while sequence[-1] <= 4000000: # 4Million
    sequence.append(sequence[-1] + sequence[-2])
sequence.pop() # delete last, as this number is too high

# 2nd step: sum the stuff

sum = 0
for item in sequence:
    if item % 2 == 0:
        sum += item
print(sum)
